/*三大场景301 302 303*/
module.exports = {
	data: [{
			"id": 301001,
			"ctg": 3,
			"subCtg": 301,
			"name": "CPA专享私播班推广",
			"time": "4月15日-5月30日",
			"address": "线上推广",
			"company": "上海泽稷教育培训有限公司",
			"show": false
		}, {
			"id": 301002,
			"ctg": 3,
			"subCtg": 301,
			"name": "魔都CFA/FRM线上试学营",
			"time": "5月（周期为7天）",
			"address": "泽稷网校学习终端及微信学习社群",
			"company": "上海泽稷教育培训有限公司",
			"show": false
		}, {
			"id": 301003,
			"ctg": 3,
			"subCtg": 301,
			"name": "上海信息消费节之“掌门教育-青春学习季",
			"time": "5月-6月",
			"address": "掌门教育平台、视频平台、微信微博平台",
			"company": "上海掌小门教育科技有限公司（掌门教育）",
			"show": false
		}, {
			"id": 301022,
			"ctg": 3,
			"subCtg": 301,
			"name": "学掌门Atstudy就业帮扶计划",
			"time": "5月18日-6月31日",
			"addressRich": true,
			"address": "学掌门官网<a href='http://www.atstudy.com' target='_blank'>www.atstudy.com</a>，微信公众号，抖音等各大平台。",
			"company": "上海博为峰软件技术股份有限公司",
			"show": false
		}, {
			"id": 301004,
			"ctg": 3,
			"subCtg": 301,
			"name": "“留住春天，云端相见”——小创客线上创意发布会",
			"time": "5月-7月",
			"address": "上海市闵行区沪闵路 6088 号二楼寓乐湾、上海市徐汇 区建国西路 652 号；寓乐湾线上平台 stemedu.cn",
			"company": "北京寓乐世界教育科技有限公司",
			"show": false
		}, {
			"id": 301005,
			"ctg": 3,
			"subCtg": 301,
			"name": "“五五消费节”——《画神闲涂鸦课堂》全集的大促活动",
			"time": "5月1日-6月1日",
			"address": "微信画神闲官方旗舰店",
			"company": "上海炫动传播有限公司",
			"show": false
		}, {
			"id": 301006,
			"ctg": 3,
			"subCtg": 301,
			"name": "赢在新高一1元抢40节初高衔接暑假名师直播课",
			"time": "5月1日-6月17日",
			"addressRich": true,
			"address": "<a href='http://t.dianping.com/deal/639434780' target='_blank'>http://t.dianping.com/deal/639434780</a> 大众点评团购",
			"company": "上海昂立教育培训有限公司",
			"show": false
		}, {
			"id": 301007,
			"ctg": 3,
			"subCtg": 301,
			"name": "流利说大学生英文阅读SHOW",
			"time": "5月6日-6月19日",
			"address": "流利说",
			"company": "上海流利说信息技术有限公司",
			"show": false
		}, {
			"id": 301008,
			"ctg": 3,
			"subCtg": 301,
			"name": "小荧星名师系列云课堂",
			"time": "5月8日-7月17日",
			"address": "小荧星",
			"company": "上海小荧星教育培训有限公司",
			"show": false
		}, {
			"id": 301009,
			"ctg": 3,
			"subCtg": 301,
			"name": "晓黑板助力校园生活安全“重启”",
			"time": "5月10日-6月14日",
			"address": "晓黑板APP",
			"company": "上海晓信信息科技有限公司",
			"show": false
		}, {
			"id": 301010,
			"ctg": 3,
			"subCtg": 301,
			"name": "流利说·阅读 大学生专属购课优惠",
			"time": "5月15日-7月16日",
			"address": "流利说",
			"company": "上海流利说信息技术有限公司",
			"show": false
		}, {
			"id": 301011,
			"ctg": 3,
			"subCtg": 301,
			"name": "《全能脑力王》科创少年培养线上活动",
			"time": "5月16日-6月17日",
			"address": "全能脑力王公众号",
			"company": "哈哈炫动卫视",
			"show": false
		}, {
			"id": 301012,
			"ctg": 3,
			"subCtg": 301,
			"name": "上海消费节·昂立好课节",
			"time": "5月17日",
			"addressRich": true,
			"address": "<p>线上：官网、官微及合作媒体等</p><p>线下：上海昂立旗下各学习中心</p>",
			"company": "上海新南洋昂立教育股份有限公司/昂立教育集团及其旗下所有上海子公司",
			"show": false
		}, {
			"id": 301013,
			"ctg": 3,
			"subCtg": 301,
			"name": "乐高®教育STEAM系列套装及FLL活动套装超值大放送",
			"time": "5月17日",
			"addressRich": true,
			"address": "<p>宜山路700号C2幢5楼</p><p>购买链接：<a href='http://annaloveydw.mikecrm.com/m9qv28E' target='_blank'>http://annaloveydw.mikecrm.com/m9qv28E</a></p>",
			"company": "上海乐承教育科技有限公司",
			"show": false
		}, {
			"id": 301014,
			"ctg": 3,
			"subCtg": 301,
			"name": "聪明米奇，让你喜欢的英语学习",
			"time": "5月17日-6月17日",
			"addressRich": true,
			"address": "<p>“聪明米奇”app、“聪明米奇”官网：</p><p><a href='http://www.smartmicky.com' target='_blank'>http://www.smartmicky.com</a></p>",
			"company": "上海千逊科技有限公司",
			"show": false
		}, {
			"id": 301015,
			"ctg": 3,
			"subCtg": 301,
			"name": "泉眼体育中小学游泳培训优惠活动",
			"time": "5月17日-6月17日",
			"address": "浦东新区兰谷路2133号—仁恒森兰运动中心游泳",
			"company": "上海泉眼体育投资管理有限公司",
			"show": false
		}, {
			"id": 301016,
			"ctg": 3,
			"subCtg": 301,
			"name": "泉眼王磊国际击剑俱乐部中小学兴趣课程——击剑",
			"time": "5月17日-6月17日",
			"address": "浦东新区黄杨路25号——泉眼王磊国际击剑俱乐部",
			"company": "上海泉眼体育投资管理有限公司",
			"show": false
		}, {
			"id": 301017,
			"ctg": 3,
			"subCtg": 301,
			"name": "以诺教育人生财富学院全民学习月",
			"time": "5月17日-6月17日",
			"address": "以诺教育小鹅通平台",
			"company": "以诺教育",
			"show": false
		}, {
			"id": 301018,
			"ctg": 3,
			"subCtg": 301,
			"name": "返校季优惠促销",
			"time": "5月25日-6月10日",
			"address": "高顿双微、官网及其他线上社交平台",
			"company": "高顿教育",
			"show": false
		}, {
			"id": 301019,
			"ctg": 3,
			"subCtg": 301,
			"name": "上海信息消费节 X VIP陪练",
			"time": "5月30日-6月7日",
			"address": "VIP陪练APP、自有新媒体矩阵",
			"company": "上海妙克信息科技有限公司",
			"show": false
		}, {
			"id": 301020,
			"ctg": 3,
			"subCtg": 301,
			"name": "2020全民跳绳“家年华”",
			"time": "5月30日-6月7日",
			"address": "跃动跳绳app、上海跃动跳绳小程序、抖音等",
			"company": "上海跃动文化传播有限公司",
			"show": false
		}, {
			"id": 301021,
			"ctg": 3,
			"subCtg": 301,
			"name": "信息消费E周学",
			"time": "5月31日-6月6日",
			"address": "易班教育、晓黑板、哔哩哔哩等",
			"company": "上海市软件行业协会",
			"show": false
		}
		/*301 id max 301022*/
		, {
			"id": 302001,
			"ctg": 3,
			"subCtg": 302,
			"name": "科麦金提果新疆好滋味促销活动",
			"time": "即日起-5月30日",
			"address": "微店app",
			"company": "科麦（上海）烘焙食品贸易有限公司",
			"show": false
		}, {
			"id": 302002,
			"ctg": 3,
			"subCtg": 302,
			"name": "上海信息消费节 广禾堂优惠",
			"time": "即日起-6月17日",
			"address": "广禾堂天猫旗舰店",
			"company": "广禾堂草本生物科技（上海）有限公司",
			"show": false
		}, {
			"id": 302003,
			"ctg": 3,
			"subCtg": 302,
			"name": "399元梦世界超级会员卡（半年卡）",
			"timeRich": true,
			"time": "<p>4月23日-5月23日（会员卡销售时间）</p><p>4月30日-6月30日（会员卡激活时间）</p>",
			"address": "元祖梦世界微信公众号/小程序",
			"company": "上海梦世界商业管理有限公司（元祖梦世界）",
			"show": false
		}, {
			"id": 302004,
			"ctg": 3,
			"subCtg": 302,
			"name": "支付宝、口碑、美团点评折扣",
			"time": "4月26日-5月30日、5月4日-5月8日",
			"address": "支付宝或口碑、美团点评",
			"company": "津味实业（上海）有限公司（85度C）",
			"show": false
		}, {
			"id": 302005,
			"ctg": 3,
			"subCtg": 302,
			"name": "竞衡八八广场790元尊享1580元套餐",
			"time": "2020年4月30日-2021年4月30日",
			"address": "上海金山假日酒店（金山区志伟路808号）",
			"company": "上海金山假日酒店（竞衡集团）",
			"show": false
		}, {
			"id": 302006,
			"ctg": 3,
			"subCtg": 302,
			"name": "麦可将亲子项目园内手作课程体验项目6-8折火锅套餐+体验",
			"timeRich": true,
			"time": "<p>4月30日-6月17日（亲子、手作体验）</p><p>4月30日-5月9日（火锅套餐+体验）<p>",
			"address": "麦可将文创园区、纸箱王餐厅",
			"company": "上海麦可将工业有限公司（麦可将文创）",
			"show": false
		}, {
			"id": 302007,
			"ctg": 3,
			"subCtg": 302,
			"name": "重走步行街 焕新上海潮生活",
			"time": "5月",
			"address": "南京东路步行街",
			"company": "小红书、黄浦区商圈企业",
			"show": false
		}, {
			"id": 302008,
			"ctg": 3,
			"subCtg": 302,
			"name": "小红书带你云逛展",
			"time": "5月或6月",
			"address": "上海博物馆",
			"company": "上海市文旅局、小红书",
			"show": false
		}, {
			"id": 302009,
			"ctg": 3,
			"subCtg": 302,
			"name": "美食买单折扣季",
			"time": "5月-6月",
			"address": "美团点评",
			"company": "美团点评（美团支付）、上海银行",
			"show": false
		}, {
			"id": 302010,
			"ctg": 3,
			"subCtg": 302,
			"name": "安心畅游节",
			"time": "5月-6月",
			"address": "美团点评",
			"company": "美团点评（美团酒旅）",
			"show": false
		}, {
			"id": 302011,
			"ctg": 3,
			"subCtg": 302,
			"name": "买菜春风复苏大促销",
			"time": "5月-6月",
			"address": "美团点评",
			"company": "美团点评（美团买菜）",
			"show": false
		}, {
			"id": 302012,
			"ctg": 3,
			"subCtg": 302,
			"name": "门店电子优惠券",
			"time": "5月1日-6月17日",
			"address": "指定上海鲜芋仙门店使用（芮欧店、虹桥丽宝广场店除外）",
			"company": "富世餐饮管理（上海）有限公司（鲜芋仙）",
			"show": false
		}, {
			"id": 302013,
			"ctg": 3,
			"subCtg": 302,
			"name": "Gsuper 绿地优选优惠活动",
			"time": "5月1日-6月17日",
			"address": "线上线下绿地优选超市",
			"company": "上海果源跨贸电子商务有限公司",
			"show": false
		}, {
			"id": 302014,
			"ctg": 3,
			"subCtg": 302,
			"name": "萌推品质英雄榜",
			"time": "5月1日-6月30日",
			"address": "趣头条",
			"company": "趣头条",
			"show": false
		}, {
			"id": 302015,
			"ctg": 3,
			"subCtg": 302,
			"name": "注春消费节活动",
			"time": "5月1日-6月30日",
			"address": "大众点评、注春人文茶饮小程序",
			"company": "上海注春餐饮管理有限公司",
			"show": false
		}, {
			"id": 302016,
			"ctg": 3,
			"subCtg": 302,
			"name": "光荣五月，快乐同行——快乐柠檬美食折扣季",
			"time": "5月5日-5月31日",
			"address": "美团点评app",
			"company": "上海快乐柠檬餐饮管理有限公司（快乐柠檬）",
			"show": false
		}, {
			"id": 302017,
			"ctg": 3,
			"subCtg": 302,
			"name": "CROWN&JanSport 双品牌联合直降",
			"time": "5月6日-5月31日",
			"addressRich": true,
			"address": "CROWN天猫旗舰店 <a href='http://tb.cn/fVUjZjv' target='_blank'>http://tb.cn/fVUjZjv</a>",
			"company": "上海冠军贸易有限公司（皇冠箱包）",
			"show": false
		}, {
			"id": 302018,
			"ctg": 3,
			"subCtg": 302,
			"name": "足不出沪，单车游“世界”",
			"time": "5月中下旬",
			"address": "美团点评",
			"company": "美团点评（美团单车）",
			"show": false
		}, {
			"id": 302019,
			"ctg": 3,
			"subCtg": 302,
			"name": "如程民宿也鸟专案",
			"time": "5月15日-12月31日",
			"address": "拼多多旗舰店（如程民宿旅游旗舰店）",
			"company": "上海东南国际旅行社有限公司",
			"show": false
		}, {
			"id": 302020,
			"ctg": 3,
			"subCtg": 302,
			"name": "信息消费节之520狂欢周",
			"time": "5月16日-5月22日",
			"address": "爱库存APP+饷店",
			"company": "上海众旦信息科技有限公司 （爱库存）",
			"show": false
		}, {
			"id": 302021,
			"ctg": 3,
			"subCtg": 302,
			"name": "盒鲜通517（我要吃）活动",
			"time": "5月17日-5月20日",
			"address": "金地（集团）股份有限公司(所在小区)  或  高华小区",
			"company": "上海津甜网络科技有限公司",
			"show": false
		}, {
			"id": 302022,
			"ctg": 3,
			"subCtg": 302,
			"name": "叮咚17宠粉周",
			"time": "5月17日-5月23日",
			"address": "叮咚买菜",
			"company": "叮咚买菜",
			"show": false
		}, {
			"id": 302023,
			"ctg": 3,
			"subCtg": 302,
			"name": "约‘惠’初夏——大额五折券，限量抢",
			"time": "5月17日-6月6日",
			"address": "天猫（儿童户外服饰） 、京东（成人户外服饰）",
			"company": "上海圣伯纳户外用品有限公司",
			"show": false
		}, {
			"id": 302024,
			"ctg": 3,
			"subCtg": 302,
			"name": "贝壳找房“年中找房季，好房享低价”",
			"time": "5月17日-6月17日",
			"address": "贝壳找房平台APP",
			"company": "贝壳找房（北京）科技有限公司",
			"show": false
		}, {
			"id": 302025,
			"ctg": 3,
			"subCtg": 302,
			"name": "HAPPY BITES宝纳儿 婴幼儿谷类辅助食品折扣季",
			"time": "5月17日-6月17日",
			"address": "宝纳儿微信商城(微信小程序)",
			"company": "上海侨好贸易有限公司（宝纳儿）",
			"show": false
		}, {
			"id": 302026,
			"ctg": 3,
			"subCtg": 302,
			"name": "永和豆浆拼多多品牌店活动券",
			"time": "5月17日-6月17日",
			"address": "拼多多平台",
			"company": "永和食品（中国）股份有限公司（永和豆浆）",
			"show": false
		}, {
			"id": 302027,
			"ctg": 3,
			"subCtg": 302,
			"name": "杜老爷厨房精致料理折扣券",
			"time": "5月17日-6月17日",
			"address": "杜老爷厨房商城(微信小程序)",
			"company": "上海侨好贸易有限公司（杜老爷厨房）",
			"show": false
		}, {
			"id": 302028,
			"ctg": 3,
			"subCtg": 302,
			"name": "宝莱纳餐饮优惠活动",
			"time": "5月17日-6月17日",
			"address": "旗下相应门店",
			"company": "上海宝莱纳餐饮有限公司",
			"show": false
		}, {
			"id": 302029,
			"ctg": 3,
			"subCtg": 302,
			"name": "理想翅客限时优惠活动",
			"time": "5月17日-6月17日",
			"address": "浦东新区耀体路308号晶耀广场东区3F",
			"company": "Wingtopia 理想翅客",
			"show": false
		}, {
			"id": 302030,
			"ctg": 3,
			"subCtg": 302,
			"name": "复工更安心 宅家也挣钱",
			"time": "5月17日-6月17日",
			"address": "e家云购",
			"company": "洁云、米娅（斯米克-东冠集团）",
			"show": false
		}, {
			"id": 302031,
			"ctg": 3,
			"subCtg": 302,
			"name": "“吃什么”特别企划--街边馋嘴小吃",
			"time": "5月17日-6月17日",
			"address": "叮咚买菜",
			"company": "叮咚买菜",
			"show": false
		}, {
			"id": 302037,
			"ctg": 3,
			"subCtg": 302,
			"name": "多力 天地合補-滴鸡精饮品优惠活动",
			"time": "5月17日-6月17日",
			"address": "微信公众号/官方商城",
			"company": "佳格投资（中国）有限公司（多力-天地合補）",
			"show": false
		}, {
			"id": 302032,
			"ctg": 3,
			"subCtg": 302,
			"name": "拌斗麦天猫优惠券",
			"time": "5月17日-6月18日",
			"address": "天猫旗舰店、淘宝直播",
			"company": "Buntleman拌斗麦天猫旗舰店",
			"show": false
		}, {
			"id": 302033,
			"ctg": 3,
			"subCtg": 302,
			"name": "上海虹桥西郊假日酒店尊享套券900元尊享价值1800元礼券",
			"time": "2020年5月17日-2021年4月30日",
			"address": "上海虹桥西郊假日酒店（青浦区沪青平公路2000号）",
			"company": "上海虹桥西郊假日酒店（竞衡集团）",
			"show": false
		}, {
			"id": 302034,
			"ctg": 3,
			"subCtg": 302,
			"delete": true,
			"name": "骑游生活指南",
			"time": "5月30日-6月30日",
			"address": "线上结合线下：徐汇线下场地+哈啰出行app弹窗页面",
			"company": "哈啰出行、徐汇区文旅局",
			"show": false
		}, {
			"id": 302035,
			"ctg": 3,
			"subCtg": 302,
			"name": "叮咚吃货狂欢周/叮咚吃货惊喜周",
			"time": "6月1日-6月7日",
			"address": "叮咚买菜",
			"company": "叮咚买菜",
			"show": false
		}, {
			"id": 302036,
			"ctg": 3,
			"subCtg": 302,
			"name": "城市狂想曲",
			"time": "6月6日-6月13日",
			"address": "携程",
			"company": "携程",
			"show": false
		}
		/*302 id max 302037*/
		, {
			"id": 303019,
			"ctg": 3,
			"subCtg": 303,
			"name": "517主题活动",
			"time": "5月17日（线上）、5月-6月（线下）",
			"address": "静安寺、上海展览中心、联通实体营业厅及线上",
			"company": "上海电信、上海移动、上海联通",
			"show": false
		}, {
			"id": 303013,
			"ctg": 3,
			"subCtg": 303,
			"name": "东方有线“五五购物节”活动",
			"time": "5月5日-6月30日",
			"address": "线上（官微、天猫旗舰店等）、东方有线各营业厅",
			"company": "东方有线",
			"show": false
		}, {
			"id": 303001,
			"ctg": 3,
			"subCtg": 303,
			"name": "“宠爱月”生活消费大促活动",
			"time": "5月9日-6月1日",
			"address": "京东到家",
			"company": "达达集团",
			"show": false
		}, {
			"id": 303014,
			"ctg": 3,
			"subCtg": 303,
			"name": "上海移动“五五购物节”517主题活动",
			"time": "5月13-6月30日",
			"address": "线上",
			"company": "上海移动",
			"show": false
		}, {
			"id": 303015,
			"ctg": 3,
			"subCtg": 303,
			"name": "北外滩来福士5G直播",
			"time": "5月15-5月19日",
			"address": "虹口北外滩来福士（东大名路1089号）等上海16个行政区的标志性的地点",
			"company": "上海电信",
			"show": false
		}, {
			"id": 303016,
			"ctg": 3,
			"subCtg": 303,
			"name": "电信商圈巡展",
			"time": "5月17日-5月23日",
			"address": "凯德龙之梦南座1楼中庭（上海市虹口区西江湾路388号）",
			"company": "上海电信",
			"show": false
		}, {
			"id": 303002,
			"ctg": 3,
			"subCtg": 303,
			"name": "户外广告线上投、消费引流线下走",
			"time": "5月17至5月30日",
			"addressRich": true,
			"address": "<a href='https://online.be-tiger.com/' target='_blank'>https://online.be-tiger.com/</a>碧虎车屏投屏热线或微信碧虎礼呈小程序",
			"company": "碧虎",
			"show": false
		}, {
			"id": 303003,
			"ctg": 3,
			"subCtg": 303,
			"name": "上海财经大学电子校园卡云闪付活动",
			"time": "5月17日-6月17日",
			"address": "上海财经大学",
			"company": "中国银联上海分公司",
			"show": false
		}, {
			"id": 303004,
			"ctg": 3,
			"subCtg": 303,
			"name": "俺来也校园云餐厅云闪付活动",
			"time": "5月17日-6月17日",
			"address": "上海建桥学院、上海电机学院、华东理工大学奉贤校区和徐汇校区、上海师范大学奉贤校区和徐汇校区、上海工程技术大学、上海应用技术大学、上海视觉艺术学院、上海交大海科院",
			"company": "中国银联上海分公司",
			"show": false
		}, {
			"id": 303005,
			"ctg": 3,
			"subCtg": 303,
			"name": "降成本，服务费手续费免收取",
			"time": "5月17日-6月17日",
			"address": "富掌柜（富友支付）",
			"company": "富掌柜（富友支付）",
			"show": false
		}, {
			"id": 303006,
			"ctg": 3,
			"subCtg": 303,
			"name": "促消费，超时免费寄存放心购",
			"time": "5月17日-6月17日",
			"address": "收件宝",
			"company": "收件宝",
			"show": false
		}, {
			"id": 303007,
			"ctg": 3,
			"subCtg": 303,
			"name": "春色已“达”、消费“到家”",
			"time": "5月17日-6月17日",
			"address": "达达集团旗下京东到家APP、小程序、网站、公众号等",
			"company": "达达集团",
			"show": false
		}, {
			"id": 303020,
			"ctg": 3,
			"subCtg": 303,
			"name": "视觉无人店及智能柜体展示",
			"time": "5月17-6月17日",
			"address": "", //待定
			"company": "上海霖罕信息科技有限公司",
			"show": false
		}, {
			"id": 303021,
			"ctg": 3,
			"subCtg": 303,
			"name": "AI人工智能终端落地拓展",
			"time": "5月17日-6月30日",
			"address": "学校、工厂、社区、办公楼、长宁区中高档小区、一兆韦德、威尔士、中体倍力、美天芙蓉江路菜场",
			"company": "深兰科技",
			"show": false
		}, {
			"id": 303022,
			"ctg": 3,
			"subCtg": 303,
			"name": "Vidlab互联网协作平台",
			"time": "5月17日-6月30日",
			"addressRich": true,
			"address": "<p>“Vidlab互联网协作平台”网址：<a href='https://www.vidlab.cn/' target='_blank'>https://www.vidlab.cn/</a></p>",
			"company": "上海领豪信息技术有限公司",
			"show": false
		}, {
			"id": 303008,
			"ctg": 3,
			"subCtg": 303,
			"name": "信息消费在银发主题培训班",
			"time": "5月25日-5月26日",
			"address": "", //待定
			"company": "上海老年大学",
			"show": false
		}, {
			"id": 303009,
			"ctg": 3,
			"subCtg": 303,
			"name": "云闪付走进老年大学活动",
			"time": "5月25日-5月26日",
			"address": "上海老年大学",
			"company": "中国银联上海分公司",
			"show": false
		}, {
			"id": 303010,
			"ctg": 3,
			"subCtg": 303,
			"name": "数字赋能商圈新基建",
			"time": "6月",
			"address": "黄浦、杨浦、徐汇、浦东、宝山等重点商圈",
			"company": "上海市信息服务业行业协会",
			"show": false
		}, {
			"id": 303023,
			"ctg": 3,
			"subCtg": 303,
			"name": "上海信息消费节商圈活动—云拿AI视觉无人店",
			"time": "6月",
			"address": "长宁区",
			"company": "上海云拿智能科技有限公司",
			"show": false
		}, {
			"id": 303024,
			"ctg": 3,
			"subCtg": 303,
			"name": "无介质浮空投影黑科技快闪体验店",
			"time": "6月",
			"address": "长宁区龙之梦",
			"company": "上海扩展现实产业研究院",
			"show": false
		}, {
			"id": 303025,
			"ctg": 3,
			"subCtg": 303,
			"name": "长宁区科普集市之信息消费产品展示",
			"time": "6月-7月",
			"address": "", //待定
			"company": "长宁区科委、长宁区科协",
			"show": false
		}, {
			"id": 303011,
			"ctg": 3,
			"subCtg": 303,
			"name": "云闪付助力智慧养老活动",
			"time": "6月1日-6月30日",
			"address": "云闪付",
			"company": "中国银联上海分公司",
			"show": false
		}, {
			"id": 303017,
			"ctg": 3,
			"subCtg": 303,
			"name": "“2020上海全球新品首发季”暨上海潮生活节启动仪式",
			"time": "6月5日-6月6日",
			"address": "白玉兰广场",
			"company": "虹口区人民政府、上海市商委",
			"show": false
		}, {
			"id": 303012,
			"ctg": 3,
			"subCtg": 303,
			"name": "购物节特别直播活动",
			"time": "6月16日",
			"address": "上海市虹口区临平路38号-2",
			"company": "上海联通",
			"show": false
		}
	],
	/*303 id max 303025*/
}
