/*三大产品101 102 103*/
module.exports = {
	data: [{
			"id": 101001,
			"ctg": 1,
			"subCtg": 101,
			"name": "￥799回收回血礼",
			"time": "4月-6月",
			"address": "爱回收",
			"company": "爱回收",
			"show": false
		}, {
			"id": 101002,
			"ctg": 1,
			"subCtg": 101,
			"name": "VR世界 抢鲜拥有",
			"time": "5月中旬",
			"addressRich": true,
			"address": "<p>电商售卖渠道：<a href=\"http://tianyiyunvr.suning.com//\" target=\"_blank\">http://tianyiyunvr.suning.com/</a></p><p>直播售卖渠道：B站（5月17日18:30-19:30）</p>",
			"company": "号百控股",
			"show": false
		}, {
			"id": 101006,
			"ctg": 1,
			"subCtg": 101,
			"name": "信息消费狂欢节",
			"time": "5月17日",
			"addressRich": true,
			"address": "<p>主会场：漕溪北路915号</p><p>分会场：中国电信各营业厅</p>",
			"company": "中国电信上海公司南区局",
			"show": false
		}, {
			"id": 101007,
			"ctg": 1,
			"subCtg": 101,
			"name": "数字赋能消费新时代",
			"time": "5月17日",
			"address": "上海",
			"company": "中国移动上海公司",
			"show": false
		}, {
			"id": 101008,
			"ctg": 1,
			"subCtg": 101,
			"name": "联通5G品鉴会：5月5G特惠活动",
			"time": "5月17日",
			"address": "腾飞大厦",
			"company": "上海联通/上海联通南区分公司",
			"show": false
		}, {
			"id": 101003,
			"ctg": 1,
			"subCtg": 101,
			"name": "5G助力信息消费",
			"time": "5月17日-6月17日",
			"address": "上海电信、上海移动、上海联通",
			"company": "上海电信、上海移动、上海联通",
			"show": false
		}, {
			"id": 101004,
			"ctg": 1,
			"subCtg": 101,
			"name": "KOO爱购",
			"time": "5月17日-6月17日",
			"address": "KOO爱花、KOO卡",
			"company": "信也科技",
			"show": false
		}, {
			"id": 101005,
			"ctg": 1,
			"subCtg": 101,
			"name": "中国电信“消费扶贫券＋5G会员流量”免费送活动",
			"time": "5月17日-12月31日",
			"addressRich": true,
			"address": "<p>暂定地址：<a href='http://5ggo.telefen.com' target='_blank'>5ggo.telefen.com</a></p><p>暂定渠道：电信营业厅APP5G专区、5G应用APP、天翼积分微信公众号、31省微信公众号等</p>",
			"company": "翼集分电子商务（上海）有限公司",
			"show": false
		}
		/*101 max 101008*/
		, {
			"id": 102001,
			"ctg": 1,
			"subCtg": 102,
			"name": "55购物节",
			"time": "5月",
			"address": "途虎养车",
			"company": "途虎养车",
			"show": false
		}, {
			"id": 102002,
			"ctg": 1,
			"subCtg": 102,
			"name": "燃“擎”岁月 幸福车生活",
			"time": "5月16日-5月17日",
			"address": "浦东长泰广场",
			"company": "上海市东昌汽车投资有限公司",
			"show": false
		}, {
			"id": 102003,
			"ctg": 1,
			"subCtg": 102,
			"name": "车轮学车节",
			"time": "5月20日-8月20日",
			"address": "车轮驾考通APP",
			"company": "车轮互联科技（上海）股份有限公司",
			"show": false
		}, {
			"id": 102004,
			"ctg": 1,
			"subCtg": 102,
			"name": "2020“拼汽车”嘉年华",
			"time": "5月23日-5月30日",
			"address": "拼多多",
			// "companyRich": true,
			"company": "拼多多、途虎养车、上汽集团",
			"show": false
		}
		/*102 max 102004*/
		, {
			"id": 103012,
			"ctg": 1,
			"subCtg": 103,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			 "companyRich": true,
			"company": "<p>上海优由智能科技有限公司</p><p>杭州海康威视数字技术股份有限公司</p><p>杭州博联智能科技股份有限公司</p><p>广州视臻信息科技有限公司</p><p>深圳市经纬纵横科技有限公司</p><p>广州奕至家居科技有限公司</p><p>联电智宅智能化技术（上海）有限公司</p><p>UIOT超级智慧家（上海）物联网科技有限公司</p>",
			"show": false
		}, {
			"id": 103013,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "杭州海康威视数字技术股份有限公司",
			"show": false
		}, {
			"id": 103001,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "杭州博联智能科技股份有限公司",
			"show": false
		}, {
			"id": 103002,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "广州视臻信息科技有限公司",
			"show": false
		}, {
			"id": 103003,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "深圳市经纬纵横科技有限公司",
			"show": false
		}, {
			"id": 103004,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "广州奕至家居科技有限公司",
			"show": false
		}, {
			"id": 103005,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "联电智宅智能化技术（上海）有限公司",
			"show": false
		}, {
			"id": 103006,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "全筑股份智能家居线上55大促",
			"time": "5月1日-6月30日",
			"address": "拼多多",
			"company": "UIOT超级智慧家（上海）物联网科技有限公司",
			"show": false
		}, {
			"id": 103007,
			"ctg": 1,
			"subCtg": 103,
			"name": "充气床8折券",
			"time": "5月8日-6月30日",
			"address": "天猫EverEarth母婴旗舰店",
			"company": "上海宇强品牌策划有限公司（EverEarth）",
			"show": false
		}, {
			"id": 103008,
			"ctg": 1,
			"subCtg": 103,
			"delete": true,
			"name": "和家直播节",
			"time": "5月10日-6月30日",
			"address": "和家直播平台、和家线上智慧门店",
			"company": "上海和颢家网络科技有限公司（和家网）",
			"show": false
		}, {
			"id": 103009,
			"ctg": 1,
			"subCtg": 103,
			"name": "体验AI智能生活，移康智能猫眼超级钜惠",
			"time": "5月16日-6月17日",
			"addressRich": true,
			"address": "<p>线上抖音直播，线下代理商渠道</p><p>线下地址：闵行区沪闵路4200号A栋</p>",
			"company": "移康智能",
			"show": false
		}, {
			"id": 103010,
			"ctg": 1,
			"subCtg": 103,
			"name": "全心全意  暖心筑家",
			"time": "5月17日-6月30日",
			"addressRich": true,
			"address": "<p>线上：公司官网、微信、抖音等平台</p><p>线下：全筑大厦、重点楼盘、项目现场</p>",
			"company": "上海全筑建筑装饰集团股份有限公司",
			"show": false
		}, {
			"id": 103011,
			"ctg": 1,
			"subCtg": 103,
			"name": "和家装修采购直播展",
			"time": "5月29日-5月31日",
			"addressRich": true,
			"address": "<p>上海市徐汇区光大会展中心（东馆）</p><p>漕宝路78号万商生活广场1楼（西南门）</p>",
			"company": "上海和颢家网络科技有限公司（和家网）",
			"show": false
		}
		/*103 max 103013*/
	]
}
