/*三大服务201 202 203*/
module.exports = {
	data: [{
			"id": 201001,
			"ctg": 2,
			"subCtg": 201,
			"name": "畅用大智慧，畅享新经济",
			"time": "5月1日-6月30日",
			"addressRich": true,
			"address": "<p>线上：选取重点推广平台、应用商城进行宣传；</p><p>线下：选取重点企业、学校等进行推广。</p>",
			"company": "大智慧",
			"show": false
		}, {
			"id": 201002,
			"ctg": 2,
			"subCtg": 201,
			"name": "随申办市民云APP购物节宣传渠道",
			"time": "5月17日",
			"address": "随申办市民云",
			"company": "万达信息股份有限公司",
			"show": false
		}, {
			"id": 201003,
			"ctg": 2,
			"subCtg": 201,
			"name": "数字经济新基建主题活动",
			"time": "5月17日-6月17日",
			"address": "美团点评",
			"company": "美团点评",
			"show": false
		}, {
			"id": 201004,
			"ctg": 2,
			"subCtg": 201,
			"name": "商米数字门店改造计划",
			"time": "5月17日-6月17日",
			"address": "五角场下沉式广场及周边门店",
			"company": "商米",
			"show": false
		}, {
			"id": 201005,
			"ctg": 2,
			"subCtg": 201,
			"name": "技术+软件 助力企业云产品优惠购",
			"time": "5月17日-6月17日",
			"address": "京东云平台、企业协会微信公众号",
			"company": "京东智联云",
			"show": false
		}, {
			"id": 201006,
			"ctg": 2,
			"subCtg": 201,
			"name": "《后疫情时代的数字化机遇》线下圆桌对话",
			"time": "5月17日-6月17日",
			"address": "优刻得",
			"company": "上海云计算促进中心",
			"show": false
		}, {
			"id": 201007,
			"ctg": 2,
			"subCtg": 201,
			"name": "“赋能传统、云领创新”云商线上",
			"time": "5月17日-6月17日",
			"address": "优刻得",
			"company": "上海云计算促进中心",
			"show": false
		}, {
			"id": 201008,
			"ctg": 2,
			"subCtg": 201,
			"name": "食汇多“安心复工助跑行动”",
			"time": "5月17日-6月17日",
			"address": "汇来米（汇付天下）",
			"company": "汇来米（汇付天下）",
			"show": false
		}, {
			"id": 201009,
			"ctg": 2,
			"subCtg": 201,
			"name": "东方财富Choice金融终端55消费节活动",
			"time": "5月17日-6月17日",
			"addressRich": true,
			"address": "<a href='http://choice.eastmoney.com/BuyingCenter' target='_blank'>http://choice.eastmoney.com/BuyingCenter</a>",
			"company": "东方财富信息股份有限公司",
			"show": false
		}, {
			"id": 201010,
			"ctg": 2,
			"subCtg": 201,
			"name": "信息消费节大促，任享百万补贴",
			"time": "5月17日-6月19日",
			"address": "启信宝、名片全能王App端",
			"company": "合合信息",
			"show": false
		}, {
			"id": 201011,
			"ctg": 2,
			"subCtg": 201,
			"name": "美团新一代门店升级",
			"time": "5月18日",
			"address": "美团点评",
			"company": "美团点评",
			"show": false
		}, {
			"id": 201012,
			"ctg": 2,
			"subCtg": 201,
			"name": "区块链技术下的电子证据存取证公证实务探索 暨“采虹印”平台发布会",
			"time": "5月30日",
			"address": "上海市新虹桥公证处",
			"company": "上海市新虹桥公证处",
			"show": false
		}, {
			"id": 201013,
			"ctg": 2,
			"subCtg": 201,
			"name": "热璞数据库消费节",
			"time": "9月30日截止",
			"addressRich": true,
			"address": "<p>官网（<a href='www.hotdb.com' target='_blank'>www.hotdb.com</a>）</p><p>邮件(<a href='mailto:service@hotdb.com'>service@hotdb.com</a>)</p>",
			"company": "上海热璞网络科技有限公司",
			"show": false
		}
		/*201 max 201013*/
		, { 
			"id": 2020001,
			"ctg": 2,
			"subCtg": 202,
			"name": "2020波克志愿者体验活动--“特别的爱给特别的你”",
			"time": "5月16日",
			"address": "上海市浦东新区成山路345号梦工坊咖啡吧",
			"company": "波克城市、波克公益基金会",
			"show": false
		}, {
			"id": 2020002,
			"ctg": 2,
			"subCtg": 202,
			"name": "元化医疗上海消费节优惠",
			"time": "5月17日",
			"address": "上海",
			"company": "元化医疗咨询服务（上海）有限公司",
			"show": false
		}, {
			"id": 2020003,
			"ctg": 2,
			"subCtg": 202,
			"name": "上海信息消费节",
			"time": "5月17日",
			"address": "徐汇区中心医院贯众互联网医院",
			"company": "徐汇区中心医院",
			"show": false
		}, {
			"id": 2020004,
			"ctg": 2,
			"subCtg": 202,
			"name": "平安好医生爆款争霸赛",
			"time": "5月17日",
			"address": "上海	",
			"company": "平安好医生",
			"show": false
		}, {
			"id": 2020005,
			"ctg": 2,
			"subCtg": 202,
			"name": "健康生活，一站配齐",
			"time": "5月17日-6月17日",
			"address": "多样屋微商城小程序、大众点评：太悠桔市花胶鸡新潮台式料理",
			"company": "多样屋生活用品（上海）有限公司",
			"show": false
		}, {
			"id": 2020006,
			"ctg": 2,
			"subCtg": 202,
			"name": "康小咖信息消费节欢乐购",
			"time": "5月17日-6月17日",
			"address": "康小咖线上商城、上海市康复辅助器具应用场景展示馆",
			"company": "上海尚栖企业服务有限公司",
			"show": false
		}
		/*202 max 2020006*/
		, {
			"id": 2030001,
			"ctg": 2,
			"subCtg": 203,
			"name": "佳核万事兴",
			"time": "4月起",
			"address": "趣头条",
			"company": "趣头条",
			"show": false
		}, {
			"id": 2030002,
			"ctg": 2,
			"subCtg": 203,
			"name": "大众文创——定制我的国潮文创",
			"time": "5月1日-5月30日",
			"addressRich": true,
			"address": "<p>手机壳定制页面：<a href='http://act.ywbjchina.com/springfes' target='_blank'>http://act.ywbjchina.com/springfes</a></p><p>帆布包定制页面：<a href='https://act.ywbjchina.com/custom-canvas-bag/index.html' target='_blank'>https://act.ywbjchina.com/custom-canvas-bag/index.html</a></p>",
			"company": "上海韵文博鉴信息科技有限公司",
			"show": false
		}, {
			"id": 2030003,
			"ctg": 2,
			"subCtg": 203,
			"name": "马卡龙“上海消费节”",
			"time": "5月17日",
			"address": "所有线上商城",
			"company": "上海卫莎网络科技有限公司/马卡龙APP、马卡龙淘宝店",
			"show": false
		}, {
			"id": 2030004,
			"ctg": 2,
			"subCtg": 203,
			"name": "起点平台拟开展电信消费节限时免费阅读活动",
			"time": "5月17日-6月17日",
			"address": "起点平台",
			"company": "阅文集团",
			"show": false
		}, {
			"id": 2030005,
			"ctg": 2,
			"subCtg": 203,
			"name": "畅看一“夏”，会员嗨购",
			"time": "5月17日-6月17日",
			"address": "爱奇艺",
			"company": "爱奇艺",
			"show": false
		}, {
			"id": 2030006,
			"ctg": 2,
			"subCtg": 203,
			"name": "QQ阅读拟开展“5.23”电信消费节优惠购会员活动",
			"time": "5月23日",
			"address": "QQ阅读App",
			"company": "阅文集团",
			"show": false
		}, {
			"id": 2030007,
			"ctg": 2,
			"subCtg": 203,
			"name": "我设计，你美丽",
			"time": "5月底起",
			"address": "线上平台",
			"company": "小红书",
			"show": false
		}, {
			"id": 2030008,
			"ctg": 2,
			"subCtg": 203,
			"name": "上海信息消费节之Uki消费狂欢季",
			"time": "6月8日-6月17日",
			"addressRich": true,
			"address": "<p>Uki app官网：<a href='http://www.neoclub.cn/' target='_blank'>http://www.neoclub.cn/</a></p><p>Uki app内派对、动态广场等栏目</p>",
			"company": "上海牛咖信息科技有限公司",
			"show": false
		}, {
			"id": 2030009,
			"ctg": 2,
			"subCtg": 203,
			"name": "虚拟商圈：打造永不落幕的线上秋叶原",
			"time": "6月8日-6月26日",
			// "addressRich": true,
			"address": "哔哩哔哩",
			"company": "哔哩哔哩",
			"show": false
		}
		/*202 max 2030009*/
	]
}
